#!/usr/bin/env python3
"""
licarsware // bundle builder
Concatenates src/*.lua into ONE executor-ready file: dist/Licarsware.lua
In dev, src files reference script.Parent.X; the bundle routes them through a
local module registry. Run from repo root:

    python3 Licarsware/tools/build.py
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))  # Licarsware/
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'dist', 'Licarsware.lua')

ORDER = ['Config', 'Util', 'Theme', 'Notifications', 'Components', 'Bindings', 'Modules', 'TargetInfo', 'Auth', 'Main', 'init']


def build():
    chunks = [
        "--!nolint\n",
        "--[[\n\tlicarsware // single-file build\n\tGenerated by tools/build.py - do not edit by hand.\n]]\n",
        "local __LW_MODULES = {}\n",
        "local __LW_PARENT = setmetatable({}, { __index = function(_, k) return __LW_MODULES[k] end })\n",
        "local function __LW_DEFINE(name, fn)\n\tlocal module = { Parent = __LW_PARENT }\n\t__LW_MODULES[name] = fn(module) or true\n\treturn __LW_MODULES[name]\nend\n",
    ]

    for name in ORDER:
        path = os.path.join(SRC, name + '.lua')
        with open(path, 'r', encoding='utf-8') as f:
            body = f.read()

        # rewrite "script.Parent" -> the bundle registry (also plain "script" self refs)
        body = body.replace('script.Parent', '__LW_SELF.Parent')
        body = body.replace("local %s = script" % name, "local %s = __LW_SELF" % name)

        chunks.append(
            "__LW_DEFINE('%s', function(__LW_SELF)\n%s\nend)\n" % (name, body)
        )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(chunks))

    size = os.path.getsize(OUT)
    print('built %s (%.1f KB)' % (OUT, size / 1024))


if __name__ == '__main__':
    build()
